name: Compilation and Format Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Compilation Check
    steps:
      - uses: actions/checkout@v3
      - run: echo "VERSION=$(cat .zigversion)" >> $GITHUB_ENV
      - uses: mlugg/setup-zig@v2
        with:
          version: ${{ env.VERSION }}
      - run: echo "zigPath=$(command -v zig | sed 's/.\{3\}$//')" >> $GITHUB_ENV
      - run: zig build -Dtarget=x86_64-linux-gnu
      - run: zig build -Dtarget=x86_64-windows-gnu
      - run: zig build -Dtarget=aarch64-linux-gnu
      - run: zig build -Dtarget=aarch64-windows-gnu
      - run: zig build -Dtarget=x86_64-macos-none
      - run: zig build -Dtarget=x86_64-macos-none
      - run: |
          if zig build -- *.zig src/*.zig src/*/*.zig src/*/*/*.zig src/*/*/*/*.zig src/*/*/*/*/*.zig src/*/*/*/*/*/*.zig src/*/*/*/*/*/*/*.zig src/*/*/*/*/*/*/*/*.zig src/*/*/*/*/*/*/*/*/*.zig src/*/*/*/*/*/*/*/*/*/*.zig | grep -q . ; then
            git diff --color=always;
            exit 1;
          fi
      - run: |
          if zig build fmt -- --zon build.zig.zon | grep -q . ; then
            git diff --color=always;
            exit 1;
          fi
